# Generated by Django 2.0.5 on 2018-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='tipology',
            field=models.IntegerField(choices=[(1, 'Top'), (2, 'Body'), (3, 'Pants'), (4, 'Shoes'), (5, 'Acessories')], default=1),
        ),
        migrations.AddField(
            model_name='games',
            name='publisher',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
