# Generated by Django 2.0.5 on 2018-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180530_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tipology',
            field=models.IntegerField(choices=[(1, 'Thriller'), (2, 'Biography'), (3, 'Comics'), (4, 'Fantasy'), (5, 'Science'), (6, 'Romance')], default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='tipology',
            field=models.IntegerField(choices=[(1, 'Magic The Gathering'), (2, 'Yugi-Oh'), (3, 'Pokemon')], default=1),
        ),
        migrations.AddField(
            model_name='games',
            name='tipology',
            field=models.IntegerField(choices=[(1, 'PS4'), (2, 'Xbox-One'), (3, 'Nintendo Wii U'), (4, 'Nintendo Switch')], default=1),
        ),
    ]
