# Generated by Django 2.0.4 on 2018-06-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180615_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='../static/img/horizon.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
